"""Changes in tenant

Revision ID: 34198a4d7e3c
Revises: 50fde2fff830
Create Date: 2025-05-17 06:01:33.608292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34198a4d7e3c'
down_revision = '50fde2fff830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
