"""Changes in tenant

Revision ID: 50fde2fff830
Revises: 09e3809c59f3
Create Date: 2025-05-17 05:12:56.507240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fde2fff830'
down_revision = '09e3809c59f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_no', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('billing_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('advance_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deposit_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('terms', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupants_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('electric_meter_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('water_meter_no', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('water_meter_no')
        batch_op.drop_column('electric_meter_no')
        batch_op.drop_column('description')
        batch_op.drop_column('occupants_count')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unit_id')
        batch_op.drop_column('terms')
        batch_op.drop_column('deposit_amount')
        batch_op.drop_column('advance_payment')
        batch_op.drop_column('billing_day')
        batch_op.drop_column('emergency_contact_no')
        batch_op.drop_column('emergency_contact')

    # ### end Alembic commands ###
